import { useState, useCallback, useRef } from "react";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogCancel,
  AlertDialogAction,
} from "@/components/ui/alert-dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { type DayPlan, type TrailDirection, trailNodes } from "@/lib/trailData";
import { type TrailPoint } from "@/lib/gpxParser";
import {
  useTrailPoints,
  findPointIndexAtDistance,
} from "@/hooks/useTrailPoints";
import { trackEvent } from "@/lib/analytics";

// Module-level flag so disclaimer is only shown once per session
let disclaimerAccepted = false;

function generateGpxXml(
  points: TrailPoint[],
  dayPlan: DayPlan,
  direction: TrailDirection
): string {
  const lines: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<gpx version="1.1" creator="Big Trail Adventures - West Highland Way Planner"',
    '  xmlns="http://www.topografix.com/GPX/1/1">',
    "  <metadata>",
    `    <name>Day ${dayPlan.day}: ${dayPlan.startNode.name} to ${dayPlan.endNode.name}</name>`,
    "    <desc>Generated by Big Trail Adventures West Highland Way Planner. For guidance only.</desc>",
    "  </metadata>",
    "  <trk>",
    `    <name>Day ${dayPlan.day}: ${dayPlan.startNode.name} → ${dayPlan.endNode.name}</name>`,
    "    <trkseg>",
  ];

  // If direction is north-to-south, the points need to be reversed
  const ordered = direction === "north-to-south" ? [...points].reverse() : points;

  for (const pt of ordered) {
    if (pt.elevation !== undefined) {
      lines.push(
        `      <trkpt lat="${pt.lat}" lon="${pt.lng}"><ele>${pt.elevation}</ele></trkpt>`
      );
    } else {
      lines.push(`      <trkpt lat="${pt.lat}" lon="${pt.lng}" />`);
    }
  }

  lines.push("    </trkseg>", "  </trk>", "</gpx>");
  return lines.join("\n");
}

interface GpxDownloadButtonProps {
  day: DayPlan;
  direction: TrailDirection;
}

const GpxDownloadButton = ({ day, direction }: GpxDownloadButtonProps) => {
  const { trailPoints, loading, cumulativeDistances, totalGpxDistance } =
    useTrailPoints();
  const [showDisclaimer, setShowDisclaimer] = useState(false);
  const [checked, setChecked] = useState(false);
  const pendingDownload = useRef(false);
  const gpxTrackedRef = useRef(false);

  const extractSegmentPoints = useCallback((): TrailPoint[] => {
    if (trailPoints.length === 0 || cumulativeDistances.length === 0) return [];

    const trailTotalDistance =
      trailNodes[trailNodes.length - 1].distanceFromStart;
    const scaleFactor = totalGpxDistance / trailTotalDistance;

    let startDist = day.startNode.distanceFromStart;
    let endDist = day.endNode.distanceFromStart;

    // For north-to-south the node distances are measured from the north end,
    // but the GPX runs south-to-north, so convert.
    if (direction === "north-to-south") {
      startDist = trailTotalDistance - day.startNode.distanceFromStart;
      endDist = trailTotalDistance - day.endNode.distanceFromStart;
    }

    const gpxStartDist = Math.min(startDist, endDist) * scaleFactor;
    const gpxEndDist = Math.max(startDist, endDist) * scaleFactor;

    const startIdx = findPointIndexAtDistance(cumulativeDistances, gpxStartDist);
    const endIdx = findPointIndexAtDistance(cumulativeDistances, gpxEndDist);

    const minIdx = Math.min(startIdx, endIdx);
    const maxIdx = Math.max(startIdx, endIdx);

    return trailPoints.slice(minIdx, maxIdx + 1);
  }, [trailPoints, cumulativeDistances, totalGpxDistance, day, direction]);

  const doDownload = useCallback(() => {
    const segmentPoints = extractSegmentPoints();
    if (segmentPoints.length === 0) return;

    if (!gpxTrackedRef.current) {
      gpxTrackedRef.current = true;
      trackEvent("custom", { event_name: "download_gpx" });
    }

    const gpxXml = generateGpxXml(segmentPoints, day, direction);
    const blob = new Blob([gpxXml], { type: "application/gpx+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `WHW-Day${day.day}-${day.startNode.name}-to-${day.endNode.name}.gpx`.replace(
      /\s+/g,
      "-"
    );
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [extractSegmentPoints, day, direction]);

  const handleClick = useCallback(() => {
    if (disclaimerAccepted) {
      doDownload();
    } else {
      setChecked(false);
      setShowDisclaimer(true);
    }
  }, [doDownload]);

  const handleAccept = useCallback(() => {
    disclaimerAccepted = true;
    setShowDisclaimer(false);
    doDownload();
  }, [doDownload]);

  if (day.isRestDay) return null;

  return (
    <>
      <Button
        variant="ghost"
        size="sm"
        onClick={handleClick}
        disabled={loading || trailPoints.length === 0}
        className="text-muted-foreground hover:text-primary gap-1.5"
      >
        <Download className="h-4 w-4" />
        Download GPX
      </Button>

      <AlertDialog open={showDisclaimer} onOpenChange={setShowDisclaimer}>
        <AlertDialogContent className="max-h-[90vh] overflow-y-auto">
          <AlertDialogHeader>
            <AlertDialogTitle>GPX File Disclaimer</AlertDialogTitle>
            <AlertDialogDescription asChild>
              <div className="text-sm text-muted-foreground space-y-3">
                <p>
                  This GPX file is provided free of charge for guidance purposes
                  only. While we make every effort to ensure accuracy at the time
                  of publication, trail conditions can and do change — sometimes
                  without warning. Paths may be closed, rerouted, or become
                  impassable due to circumstances entirely beyond our control.
                </p>
                <p>
                  You are solely responsible for your own safety and the safety
                  of anyone in your group. This file does not replace proper
                  navigation skills, up-to-date local knowledge, or a physical
                  map and compass. Always check current trail conditions with
                  local authorities before setting out, and be prepared to turn
                  back or find an alternative route if conditions require it.
                </p>
                <p>
                  Big Trail Adventures accepts no liability whatsoever for any
                  loss, injury, damage, or inconvenience — however caused —
                  arising from the use of, or reliance upon, this GPX file or
                  any information contained within it. Use of this file
                  constitutes acceptance of these terms.
                </p>
              </div>
            </AlertDialogDescription>
          </AlertDialogHeader>

          <div className="flex items-start gap-3 pt-2">
            <Checkbox
              id="gpx-disclaimer"
              checked={checked}
              onCheckedChange={(v) => setChecked(v === true)}
            />
            <label
              htmlFor="gpx-disclaimer"
              className="text-sm font-medium leading-snug cursor-pointer select-none"
            >
              I have read and accept the above terms
            </label>
          </div>

          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction disabled={!checked} onClick={handleAccept}>
              Download GPX
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
};

export default GpxDownloadButton;
